const fs = require('fs');

const path = 'lib/l10n/app_en.arb';
let raw = fs.readFileSync(path, 'utf8');
let json = JSON.parse(raw);

const translations = {
  "arenaAnomalieDTectE": "ANOMALY DETECTED",
  "arenaLUtilisationDUne": "The use of a simulated GPS position is strictly forbidden by Valerion protocols. Your session has been interrupted.",
  "arenaAlerteZoneCompromiseRecalcul": "ALERT: COMPROMISED ZONE - TACTICAL RECALCULATION",
  "arenaSignalementEnvoyUplinkTactique": "REPORT SENT - TACTICAL UPLINK ESTABLISHED",
  "arenaVRificationDesProtocoles": "VERIFYING ALPHA PROTOCOLS...",
  "arenaRivalGhost": "RIVAL GHOST",
  "arenaDFiPerformanceD": "PERFORMANCE CHALLENGE DETECTED",
  "arenaPerformanceExceptionnelle": "Exceptional performance.",
  "arenaVoulezVousGraverCe": "Do you want to engrave this track in the rivals section so others can face your Ghost?",
  "arenaGraverLeTrac": "ENGRAVE TRACK",
  "arenaGravureDansLeColis": "ENGRAVING IN THE COLISEUM IN PROGRESS...",
  "arenaSessionEnregistrETrac": "SESSION RECORDED: TRACK SHARED WITH THE COMMUNITY.",
  "arenaSynchronisationDeLaSession": "SYNCHRONIZING SESSION...",
  "arenaSessionTerminE": "SESSION FINISHED",
  "arenaAucuneDonnEGps": "NO GPS DATA",
  "arenaAllureMoy": "AVG PACE",
  "arenaAnalyseDeLaVitesse": "SPEED ANALYSIS (KM/H)",
  "arenaRCompensesAcquises": "REWARDS ACQUIRED",
  "arenaRetournerAuMenu": "RETURN TO MENU",
  "arenaLArNe": "THE ARENA",
  "arenaTricheDTectE": "CHEAT DETECTED: Please disable mock locations.",
  "arenaDClarezVosR": "DECLARE YOUR RESULTS TO TAKE CONTROL.",
  "arenaErreurVousDevezEffectuer": "ERROR: YOU MUST PERFORM AT LEAST ONE REPETITION.",
  "arenaConquRir": "CONQUER",
  "arenaRadarDeBastions": "BASTION RADAR",
  "arenaProtocoleOsirionScan": "OSIRION PROTOCOL: SCANNING...",
  "arenaQuartierSCurisAucun": "SECURED DISTRICT: NO BASTION",
  "arenaSignalTropFaibleRapprochez": "WEAK SIGNAL: Get closer than 50m.",
  "arenaAucunQuipementSpCifique": "No specific equipment detected by OSM sensors.",
  "arenaPositionSatelliteGuidage": "SATELLITE POSITION (GUIDANCE)",
  "arenaMissionDeReconnaissance": "RECONNAISSANCE MISSION",
  "arenaFournissezLeRenseignementVisuel": "PROVIDE VISUAL INTELLIGENCE",
  "arenaCapturerLIntel": "CAPTURE INTEL",
  "arena250Xp": "+250 XP",
  "arenaErreurSignalGpsPosition": "GPS SIGNAL ERROR: Position not detected. Wait for GPS fix.",
  "arenaRenseignementTransmis250Xp": "INTELLIGENCE TRANSMITTED: +250 XP! OSIRION thanks you, Scout.",
  "arenaImpossibleDeLancerLe": "Unable to launch satellite guidance.",
  "arenaViolationDeSCurit": "SECURITY VIOLATION",
  "arenaVousTesTropLoin": "YOU ARE TOO FAR",
  "arenaAutorisationRequise": "AUTHORIZATION REQUIRED",
  "arenaSoyezLePremierGraver": "Be the first to engrave your achievement!",
  "arenaMatchmakingGlobalAlphaDisponible": "GLOBAL ALPHA MATCHMAKING AVAILABLE",
  "arenaModeMatchmakingRelatifGlobal": "Mode: Global Relative Matchmaking",
  "arenaVousAllezAffronterLe": "You will face the ghost of this runner on your own terrain.",
  "arenaLancerLeDuel": "START DUEL",
  "arenaGNRerLa": "GENERATE LOOP",
  "arenaLesTerritoires": "THE TERRITORIES",
  "arenaConquTesGOlocalis": "Geolocated conquests via hexagonal grid. Run to dominate your district.",
  "arenaDVeloppementEnCours": "UNDER DEVELOPMENT (MAP ENGINE)",
  "arenaValiderLaDestination": "CONFIRM DESTINATION",
  "arenaOsirionPerformance": "OSIRION PERFORMANCE",
  "arenaAucunTracDisponible": "NO TRACK AVAILABLE",
  "arenaEngineeredByValerion": "ENGINEERED BY VALERION",
  "arenaSessionTropCourtePour": "SESSION TOO SHORT FOR ANALYSIS",
  "arenaPartageDePerformance": "PERFORMANCE SHARE",
  "arenaPerformancePartagEAvec": "Performance successfully shared 🚀",
  "arenaRSeauAthlTes": "ATHLETES NETWORK",
  "arenaQuipesClubs": "TEAMS & CLUBS",
  "libraryLeOnAncrE": "Lesson anchored in the Golden Book. +10 XP.",
  "librarySessionTerminE": "Session Finished",
  "libraryProuesseIntellectuelleValidE": "Intellectual prowess validated. +15 Wisdom XP.",
  "libraryLaForgeDeL": "THE FORGE OF THE MIND",
  "libraryMigrationFirestoreRUssie": "✅ Firestore migration successful (Books, Audios, Relics)!",
  "libraryMigrerCloud": "MIGRATE CLOUD",
  "libraryCollectionsFirestorePurgEs": "🧹 Firestore collections purged (Books, Audios, Relics, Dojo)!",
  "librarySagesseActuelle": "Current Wisdom",
  "libraryNePasDRanger": "DO NOT DISTURB ACTIVATED",
  "libraryContratDHonneur": "CONTRACT OF HONOR",
  "libraryLaVieNeVaut": "\"The unexamined life is not worth living.\"",
  "libraryAiJeTFid": "Was I true to my values and goals today?",
  "libraryScellerLeContrat": "SEAL CONTRACT",
  "libraryOuvrirLeLivreD": "Open the Golden Book (Archives)",
  "libraryRCupRationMentale": "MENTAL RECOVERY",
  "libraryDevenezAlpha": "Become Alpha+",
  "libraryDBloquezLeMode": "Unlock offline mode and niche topics.",
  "libraryThMe": "THEME",
  "libraryPourquoiLIntGrer": "WHY INTEGRATE IT?",
  "libraryCitationCl": "KEY QUOTE",
  "libraryLancerLaLecture": "START READING",
  "libraryAucunLivreTrouv": "No book found.",
  "libraryNouveauxContenusSynchronisS": "New content synchronized with Firestore",
  "libraryAnnulerLaLecture": "Cancel reading",
  "libraryQuelleLeOnAvez": "What lesson did you learn today?",
  "libraryHagakureLeCodeDu": "Hagakure: The Code of the Samurai",
  "libraryLObstacleEstLe": "The Obstacle is the Way",
  "libraryLeManuel": "The Enchiridion",
  "libraryPensEsPourMoi": "Meditations",
  "libraryDeLaBriVet": "On the Shortness of Life",
  "libraryDeLaTranquillitDe": "On the Tranquility of the Mind",
  "libraryConsolationDeLaPhilosophie": "The Consolation of Philosophy",
  "libraryAtomicHabits": "Atomic Habits",
  "libraryLaPsychologieDesFoules": "The Crowd: A Study of the Popular Mind",
  "libraryLArtDAvoir": "The Art of Being Right",
  "libraryLesCaractRes": "Characters",
  "libraryTraitDeLaVie": "Treatise on Elegant Living",
  "libraryLArtDeLa": "The Art of War",
  "libraryLePrince": "The Prince",
  "libraryTraitDesCinqRoues": "The Book of Five Rings",
  "libraryTaoTeKing": "Tao Te Ching",
  "libraryLeLivreDuCourtisan": "The Book of the Courtier",
  "libraryTempsCoul": "TIME UP",
  "librarySouhaitezVousContinuerLire": "Do you want to continue reading for 15 more minutes, or seal the session and write your contract of honor?",
  "libraryForger15Min": "FORGE (+15 MIN)",
  "libraryScellerLaSession": "SEAL SESSION",
  "libraryTempsRestant": "Time Remaining",
  "arsenalLArsenal": "THE ARSENAL",
  "arsenalPossD": "OWNED",
  "arsenalPacteDuForgeron": "Blacksmith's Pact",
  "arsenalVotreSacEstVide": "Your bag is empty. Visit the Blacksmith.",
  "laboratoryInitialisationDeLaVision": "Initializing AI vision...",
  "laboratoryEntraNementEnPause": "Training paused (Simulation)",
  "laboratoryLeLaboratoire": "THE LABORATORY",
  "laboratoryAucunProfilDTect": "No profile detected.",
  "laboratoryVosStatistiquesDeCombat": "Your combat statistics (Strength XP, Wisdom, Pull-ups/Push-ups Records) cannot be manually altered. They are governed exclusively by the Dojo's Artificial Intelligence and your validated workouts.",
  "laboratorySynchroniserLesModifications": "SYNCHRONIZE MODIFICATIONS",
  "laboratoryAvatarMisJourDans": "Avatar updated in the Cloud.",
  "laboratoryStatutDeSynchronisation": "Synchronization Status",
  "laboratorySauvegardeForcER": "Forced backup successful.",
  "laboratoryCacheEtFichiersTemporaires": "Cache and temporary files cleared.",
  "laboratoryAttentionCesFonctionnalitS": "WARNING: These experimental features may be unstable or drain battery life.",
  "laboratoryCentreDAideOsirion": "OSIRION HELP CENTER",
  "laboratoryDiagnosticSystMe": "SYSTEM DIAGNOSTIC",
  "laboratorySignalementValerion": "VALERION REPORT",
  "laboratoryTypeDeRetour": "FEEDBACK TYPE",
  "laboratoryNoteLesDonnEs": "Note: Diagnostic data (OS, Version, Level) will be automatically attached.",
  "laboratoryChecDirectOuvertureDu": "Direct failure. Opening share menu...",
  "smartMapParcoursDeSant": "Health Trail",
  "smartMapParcoursOptimisS": "Optimized Trails",
  "smartMapDCouvrezDesItin": "Discover routes adapted to your level.",
  "smartMapLArNe": "THE ARENA",
  "smartMapSignalDeDTresse": "Distress signal ready to be sent.",
  "smartMapDMarrer": "START",
  "smartMapPhaseDInitialisationAr": "Arena initialization phase...",
  "smartMapParcNord": "North Park",
  "smartMapDistanceCible": "Target Distance",
  "smartMapGNRer3": "GENERATE 3 CLOVER OPTIONS",
  "smartMapSYRendreGps": "Go there (GPS)",
  "smartMapOmbrePersonnelle": "Personal Shadow",
  "smartMapRecord2845": "Record: 28:45",
  "smartMapCourezContreVotrePerformance": "Run against your February 12th performance on the 6km loop. The audio will give your delay/lead.",
  "smartMapLeaderboardsSegments": "SEGMENTS LEADERBOARDS",
  "smartMapCoachVocalDucking": "Voice Coach (Ducking)",
  "smartMapAttNueSpotifyLors": "Attenuates Spotify during directions",
  "smartMapSafetySync": "Safety Sync",
  "smartMapPartageEnDirectContact": "Live Sharing (Emergency contact)",
  "splashOSIR": "O S I R I O N",
  "splashForceLoyautSagesse": "STRENGTH . LOYALTY . WISDOM",
  "visionAiVisionAiActive": "Active AI Vision",
  "authUnEmailContenantUn": "An email containing a reset link has been sent to this address.",
  "authInitieTaConnexionAu": "Initiate your connection to the system",
  "authCodeDAccS": "Lost access code?",
  "authNouveauCandidatRejoindreL": "New candidate? Join the OSIRION Order.",
  "authIdentifiantAlphaEmail": "Alpha Identifier (Email)",
  "authCodeDeSCurit": "Security Code",
  "authNouvelleRecrue": "NEW RECRUIT",
  "authLReDOsirion": "The era of OSIRION awaits. Create your profile.",
  "authSEnrLerDans": "ENROLL IN OSIRION",
  "authNomDeCodePseudo": "Code name (Nickname)",
  "authMotDePasseD": "Access password",
  "authBienvenueDansLOrdre": "WELCOME TO THE ORDER",
  "authForceLoyautSagesse": "Strength • Loyalty • Wisdom",
  "authSEnrLerMaintenant": "ENROLL NOW",
  "authDJMembreDe": "ALREADY A MEMBER OF THE ORDER",
  "profileUploadDeLaPhoto": "Uploading photo...",
  "profileProfilJour": "Profile up to date!",
  "profileDualTrack": "DUAL-TRACK",
  "profileCalendrierDeCohRence": "CONSISTENCY CALENDAR",
  "profileLaboratoireBiomTrique": "BIOMETRIC LABORATORY",
  "profileRegistreLeDojoIa": "LOG: THE DOJO (AI)",
  "profileGestionDuSanctuaire": "SANCTUARY MANAGEMENT",
  "profileLeCodexDeL": "THE MIND CODEX",
  "profileSRieDHonneur": "HONOR STREAK",
  "profileJoursConsCutifs": "CONSECUTIVE DAYS",
  "profileArchivesDuJournal": "JOURNAL ARCHIVES",
  "profileErreurLorsDuChargement": "Error loading archives.",
  "profileRegistreLArNe": "LOG: THE ARENA (GPS)",
  "profilePassAlphaInactif": "ALPHA+ PASS INACTIVE",
  "profileSoutenirLeProjetEt": "Support the project and unlock advanced stats.",
  "profileAvisFeedback": "Reviews & Feedback",
  "profileVotreAvisCompte": "Your opinion matters",
  "profileAidezNousAmLiorer": "Help us improve OSIRION for the Winter Arc.",
  "profileMerciPourVotreAvis": "Thank you for your feedback!",
  "profilePartagezVotreExpRience": "Share your experience...",
  "profileMDitationAchevE": "✨ Meditation completed. +20 Wisdom XP.",
  "profileMDitationDeepWork": "MEDITATION & DEEP WORK",
  "profileRInitialiser": "Reset"
};

for (const [key, value] of Object.entries(translations)) {
  if (json[key] !== undefined) {
    json[key] = value;
  }
}

fs.writeFileSync(path, JSON.stringify(json, null, 2));
console.log('All remaining translations applied.');
