enum CameraAngle { face, profile }

class ExerciseConfig {
  final String id;
  final String name;
  final String description;
  final String targetBodyPart; // e.g., 'UPPER', 'LOWER', 'CORE', 'FULL_BODY', 'LIMB'
  final String trainingType; // e.g., 'FORCE', 'ENDURANCE', 'SKILL'
  final int defaultXpPerRep;
  final String unit; // 'reps' ou 'seconds'
  final String? videoUrl; // URL ou chemin d'asset de la vidéo
  final CameraAngle requiredCameraAngle;

  const ExerciseConfig({
    required this.id,
    required this.name,
    required this.description,
    required this.targetBodyPart,
    required this.trainingType,
    this.defaultXpPerRep = 10,
    this.unit = 'reps',
    this.videoUrl,
    this.requiredCameraAngle = CameraAngle.profile,
  });

  factory ExerciseConfig.fromMap(String id, Map<String, dynamic> map) {
    return ExerciseConfig(
      id: id,
      name: map['name'] ?? '',
      description: map['description'] ?? '',
      targetBodyPart: map['targetBodyPart'] ?? 'FULL_BODY',
      trainingType: map['trainingType'] ?? 'FORCE',
      defaultXpPerRep: map['defaultXpPerRep'] ?? 10,
      unit: map['unit'] ?? 'reps',
      videoUrl: map['videoUrl'],
      requiredCameraAngle: map['requiredCameraAngle'] == 'face'
          ? CameraAngle.face
          : CameraAngle.profile,
    );
  }

  Map<String, dynamic> toMap() {
    return {
      'name': name,
      'description': description,
      'targetBodyPart': targetBodyPart,
      'trainingType': trainingType,
      'defaultXpPerRep': defaultXpPerRep,
      'unit': unit,
      'videoUrl': videoUrl,
      'requiredCameraAngle': requiredCameraAngle.name,
    };
  }

  /// Vérifie si cet exercice est supporté par le moteur de vision IA
  bool get hasAiSupport {
    final lowerId = id.toLowerCase();
    return lowerId.contains("pushups") ||
        lowerId.contains("pompes") ||
        lowerId.contains("tractions") ||
        lowerId.contains("pull_ups") ||
        lowerId.contains("dips") ||
        lowerId.contains("sphinx") ||
        lowerId.contains("squat") ||
        lowerId.contains("fente") ||
        lowerId.contains("relevs") ||
        lowerId.contains("v_ups") ||
        lowerId.contains("pike") ||
        lowerId.contains("jumping") ||
        lowerId.contains("sauts");
  }
}

// Catalogue d'exercices disponibles
class ValerionExercises {
  static const List<ExerciseConfig> catalogue = [
    ExerciseConfig(
      id: "sw_ful_muscle_ups",
      name: "Muscle-ups",
      description: "stricts, sans élan",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_front_lever",
      name: "Front Lever",
      description: "maintien isométrique ou tirages",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_ful_back_lever",
      name: "Back Lever",
      description: "maintien isométrique",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_ful_tractions_un_bras",
      name: "Tractions à un bras",
      description: "ou Archer pull-ups très lentes",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_pompes_un_bras",
      name: "Pompes à un bras",
      description: "ou Archer push-ups",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_pistol_squats",
      name: "Pistol Squats",
      description: "très lents, contrôle de la descente",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_planche",
      name: "Planche",
      description: "Tuck planche, Straddle ou Full",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_ful_pompes_en_poirier",
      name: "Pompes en poirier",
      description: "Handstand push-ups - HSPU",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_human_flag",
      name: "Human Flag",
      description: "Drapeau",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_dragon_flags",
      name: "Dragon Flags",
      description: "descente contrôlée au maximum",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_dips_aux_anneaux_ou_dips_bulgares",
      name: "Dips aux anneaux ou Dips bulgares",
      description: "sur barre droite",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_nordic_hamstring_curls",
      name: "Nordic Hamstring Curls",
      description: "pieds bloqués sous la barre basse du parc",
      targetBodyPart: "FULL_BODY",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.face,
    ),
    ExerciseConfig(
      id: "sw_ful_burpees",
      name: "Burpees",
      description: "avec pompe et saut",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 10,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.profile,
    ),
    ExerciseConfig(
      id: "sw_ful_tractions_sautes",
      name: "Tractions sautées",
      description: "Jumping pull-ups",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_pompes_claques",
      name: "Pompes claquées",
      description: "Clapping push-ups",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_squats_sauts",
      name: "Squats sautés",
      description: "Jump squats",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_mountain_climbers",
      name: "Mountain Climbers",
      description: "rythme sprint",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_fentes_sautes",
      name: "Fentes sautées",
      description: "Jumping lunges",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_bear_crawl",
      name: "Bear Crawl",
      description: "Marche de l'ours sur la longueur du spot",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_jumping_jacks",
      name: "Jumping Jacks",
      description: "Renforcement spécifique.",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_sprawls",
      name: "Sprawls",
      description: "Burpees sans la pompe",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.face,
    ),
    ExerciseConfig(
      id: "sw_ful_muscle_ups_kipping",
      name: "Muscle-ups kipping",
      description: "avec élan, pour enchaîner les reps",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_tuck_jumps",
      name: "Tuck jumps",
      description: "Sauts genoux poitrine",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_ful_sauts_de_singe",
      name: "Sauts de singe",
      description: "Monkey jumps / déplacements latéraux au sol",
      targetBodyPart: "FULL_BODY",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.face,
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_pseudo_planche",
      name: "Pompes Pseudo-Planche",
      description: "PPPU - mains au niveau des hanches",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_upp_tractions_lestes",
      name: "Tractions lestées",
      description: "si tu as un gilet",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_russian_dips",
      name: "Russian Dips",
      description: "Dips avec passage sur les coudes",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.profile,
    ),
    ExerciseConfig(
      id: "sw_upp_sphinx_push_ups",
      name: "Sphinx push-ups",
      description: "Extensions triceps au sol, poids du corps",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_typewriter_pull_ups",
      name: "Typewriter pull-ups",
      description: "Tractions machine à écrire",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_l_sit_to_handstand",
      name: "L-sit to Handstand",
      description: "sur parallettes ou au sol",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_front_lever_raises",
      name: "Front lever raises",
      description: "Tirages bras tendus de la verticale à l'horizontale",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_diamant",
      name: "Pompes Diamant",
      description: "tempo très lent : 4 sec descente, 2 sec pause",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pelican_curls",
      name: "Pelican Curls",
      description: "aux anneaux ou sous une barre basse",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_tractions_en_supination",
      name: "Tractions en supination",
      description: "Chin-ups",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_upp_impossible_dips",
      name: "Impossible Dips",
      description: "extensions triceps sur barres parallèles",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_en_quilibre",
      name: "Pompes en équilibre",
      description: "HSPU",
      targetBodyPart: "UPPER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_tractions_pronation",
      name: "Tractions pronation",
      description: "séries max",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_classiques",
      name: "Pompes classiques",
      description: "séries max",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_dips_sur_barres_parallles",
      name: "Dips sur barres parallèles",
      description: "rythme rapide",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_tractions_australiennes",
      name: "Tractions australiennes",
      description: "Rowing poids du corps sous une barre basse",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_larges",
      name: "Pompes larges",
      description: "mains très écartées",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.profile,
    ),
    ExerciseConfig(
      id: "sw_upp_commando_pull_ups",
      name: "Commando pull-ups",
      description: "Tractions prise alternée d'un côté et de l'autre de la barre",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_dclines",
      name: "Pompes déclinées",
      description: "pieds sur un banc ou un muret",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pompes_surleves",
      name: "Pompes surélevées",
      description: "mains sur un banc",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_dips_sur_banc",
      name: "Dips sur banc",
      description: "Bench dips",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_pike_push_ups",
      name: "Pike push-ups",
      description: "Pompes piquées pour les épaules, rythme soutenu",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_tractions_prise_serre",
      name: "Tractions prise serrée",
      description: "Renforcement spécifique.",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_upp_shadow_boxing_trs_rapide",
      name: "Shadow boxing très rapide",
      description: "focus sur l'engagement des bras et épaules",
      targetBodyPart: "UPPER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_pistol_squats",
      name: "Pistol Squats",
      description: "descendre jusqu'au mollet",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_shrimp_squats",
      name: "Shrimp Squats",
      description: "unilatéral, genou arrière touche le sol",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_squats_cosaques",
      name: "Squats Cosaques",
      description: "fentes latérales très profondes et lentes",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_fentes_bulgares",
      name: "Fentes Bulgares",
      description: "pied arrière sur le banc du parc, descente lente",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_sissy_squats",
      name: "Sissy Squats",
      description: "focus quadriceps extrême, poids du corps vers l'arrière",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_natural_glute_ham_raise",
      name: "Natural Glute Ham Raise",
      description: "au sol, si tu peux bloquer tes chevilles",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_lvations_de_mollets_une_jambe",
      name: "Élévations de mollets à une jambe",
      description: "sur le bord d'un trottoir, maintien en haut",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_low_hover_lunges",
      name: "Hover Lunges",
      description: "Fentes sans jamais poser le genou au sol ni tendre la jambe",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_squats_profonds_avec_une_pause_isomtrique_de_10_secondes_en_bas",
      name: "Squats profonds avec une pause isométrique de 10 secondes en bas",
      description: "Renforcement spécifique.",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_low_harter_squats",
      name: "Harter Squats",
      description: "Squats sur la pointe des pieds, talons collés",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_glute_bridge_unilatral",
      name: "Glute Bridge unilatéral",
      description: "au sol, poussée lente du bassin",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_fentes_avant_marches",
      name: "Fentes avant marchées",
      description: "tempo très lent, pas de rebond",
      targetBodyPart: "LOWER",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_squats_poids_du_corps",
      name: "Squats poids du corps",
      description: "séries de 50 à 100 reps",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_box_jumps",
      name: "Box Jumps",
      description: "Sauts sur un muret ou un gros bloc",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_fentes_sautes_alternes",
      name: "Fentes sautées alternées",
      description: "Renforcement spécifique.",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_broad_jumps",
      name: "Broad Jumps",
      description: "Sauts en longueur à pieds joints dans l'herbe",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
      requiredCameraAngle: CameraAngle.profile,
    ),
    ExerciseConfig(
      id: "sw_low_step_ups_explosifs",
      name: "Step-ups explosifs",
      description: "montées rapides sur un banc",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_sauts_de_patineur",
      name: "Sauts de patineur",
      description: "Skater jumps latéraux",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_sprint_navette",
      name: "Sprint navette",
      description: "aller-retour sur 10 mètres",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_fentes_marches",
      name: "Fentes marchées",
      description: "rythme très rapide",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_squats_sauts",
      name: "Squats sautés",
      description: "Jump squats",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_high_knees",
      name: "High knees",
      description: "Montées de genoux sur place à vitesse max",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_lvations_de_mollets_deux_jambes",
      name: "Élévations de mollets à deux jambes",
      description: "rebonds rapides",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_low_course_en_gradins_ou_escaliers",
      name: "Course en gradins ou escaliers",
      description: "si disponibles près du spot",
      targetBodyPart: "LOWER",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_relevs_de_jambes_la_barre_fixe",
      name: "Relevés de jambes à la barre fixe",
      description: "Toes to bar",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_dragon_flags",
      name: "Dragon Flags",
      description: "sur un banc",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_l_sit",
      name: "L-sit",
      description: "maintien isométrique au sol ou sur parallettes",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_v_sit",
      name: "V-sit",
      description: "évolution du L-sit, jambes levées plus haut",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_windshield_wipers",
      name: "Windshield Wipers",
      description: "Essuie-glaces suspendus à la barre",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_human_flag",
      name: "Human Flag",
      description: "maintien ou tentatives",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_planche_lean",
      name: "Planche Lean",
      description: "Planche penchée au maximum en avant, bassin rétroversé",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_ab_rollout",
      name: "Ab Rollout",
      description: "avec des anneaux ras du sol ou un t-shirt glissant sur l'herbe",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_hanging_oblique_raises",
      name: "Hanging Oblique Raises",
      description: "Relevés de genoux obliques à la barre, avec pause",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_hollow_body_hold",
      name: "Hollow Body Hold",
      description: "Gainage cuillère, bas du dos plaqué, maintien long",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_dragon_flag_flutter_kicks",
      name: "Dragon Flag flutter kicks",
      description: "Petits battements en position de Dragon Flag",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_back_lever_hold",
      name: "Back Lever hold",
      description: "engage massivement les lombaires et la ceinture abdo",
      targetBodyPart: "CORE",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_crunches_classiques_au_sol",
      name: "Crunches classiques au sol",
      description: "Renforcement spécifique.",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_bicyclette",
      name: "Bicyclette",
      description: "Bicycle crunches",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_gainage_coudes",
      name: "Gainage coudes",
      description: "Planche - tenir le temps maximum",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 1,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_cor_mountain_climbers_croiss",
      name: "Mountain Climbers croisés",
      description: "genou vers coude opposé",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_v_ups",
      name: "V-ups",
      description: "Portefeuille rapide",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_flutter_kicks",
      name: "Flutter kicks",
      description: "Battements de jambes au sol, ras de l'herbe",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_scissors",
      name: "Scissors",
      description: "Ciseaux croisés au sol",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_gainage_latral",
      name: "Gainage latéral",
      description: "Side plank",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_russian_twists",
      name: "Russian Twists",
      description: "sans poids, focus sur la vitesse de rotation",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_relevs_de_genoux_suspendus_la_barre",
      name: "Relevés de genoux suspendus à la barre",
      description: "Knee raises, rythme rapide",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_crunches_inverss",
      name: "Crunches inversés",
      description: "Reverse crunches",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_cor_jackknives_assis_sur_un_banc_de_parc",
      name: "Jackknives assis sur un banc de parc",
      description: "Renforcement spécifique.",
      targetBodyPart: "CORE",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_scapular_pull_ups",
      name: "Scapular Pull-ups",
      description: "Tractions scapulaires, bras tendus, haussements d'épaules",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_scapular_push_ups",
      name: "Scapular Push-ups",
      description: "Pompes scapulaires au sol",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_maintien_isomtrique_en_bas_des_dips",
      name: "Maintien isométrique en bas des Dips",
      description: "étirement actif des pecs/épaules",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_maintien_isomtrique_menton_au_dessus_de_la_barre",
      name: "Maintien isométrique menton au-dessus de la barre",
      description: "Lock-off",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_chaise_contre_un_poteau_ou_muret",
      name: "Chaise contre un poteau ou muret",
      description: "Wall sit",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_pont",
      name: "Pont",
      description: "Bridge hold",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_maintien_de_fausse_prise",
      name: "Maintien de fausse prise",
      description: "False grip",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_wrist_push_ups",
      name: "Wrist Push-ups",
      description: "Pompes sur les poignets ou dos des mains, sur les genoux",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_lvations_de_mollets_unilatrales",
      name: "Élévations de mollets unilatérales",
      description: "maintien de 10 sec en contraction maximale",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_german_hang",
      name: "German Hang",
      description: "suspension inversée aux anneaux/barre, étirement actif des épaules",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 25,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_maintien_isomtrique_en_fente",
      name: "Maintien isométrique en fente",
      description: "genou arrière à 1 cm du sol",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_planche_latrale_toile",
      name: "Planche latérale étoile",
      description: "Star plank",
      targetBodyPart: "LIMB",
      trainingType: "FORCE",
      defaultXpPerRep: 10,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_dead_hang",
      name: "Dead Hang",
      description: "Suspension passive à la barre - le plus longtemps possible pour décompresser",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 1,
      unit: 'seconds',
    ),
    ExerciseConfig(
      id: "sw_lim_pompes_au_mur",
      name: "Pompes au mur",
      description: "Wall push-ups - séries très longues, effort minime",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_rotations_dpaules",
      name: "Rotations d'épaules",
      description: "Arm circles à vide - séries de 100",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_tractions_australiennes_trs_inclines",
      name: "Tractions australiennes très inclinées",
      description: "presque debout, tirages légers",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_step_ups_trs_lents_et_sans_lan_sur_un_tout_petit_trottoir",
      name: "Step-ups très lents et sans élan sur un tout petit trottoir",
      description: "Renforcement spécifique.",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_balanciers_de_jambe",
      name: "Balanciers de jambe",
      description: "Leg swings avant/arrière et latéraux pour la hanche",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_rotations_du_buste_debout",
      name: "Rotations du buste debout",
      description: "Twists légers",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_flexionsextensions_de_poignets_dans_le_vide",
      name: "Flexions/extensions de poignets dans le vide",
      description: "pour les avant-bras",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_montes_sur_pointes_de_pieds_deux_pieds_au_sol",
      name: "Montées sur pointes de pieds à deux pieds au sol",
      description: "moulinage très rapide et léger",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_cat_cow",
      name: "Cat-cow",
      description: "Dos rond / Dos creux au sol sur l'herbe",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_lvations_frontales_et_latrales_vide",
      name: "Élévations frontales et latérales à vide",
      description: "sans poids, focus sur le mouvement",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
    ExerciseConfig(
      id: "sw_lim_shadow_boxing_trs_lent_et_relch",
      name: "Shadow boxing très lent et relâché",
      description: "Flow, déliement articulaire",
      targetBodyPart: "LIMB",
      trainingType: "ENDURANCE",
      defaultXpPerRep: 5,
      unit: 'reps',
    ),
  ];
  static List<ExerciseConfig> getByTargetAndType(String target, String type) {
    return catalogue
        .where((e) => e.targetBodyPart == target && e.trainingType == type)
        .toList();
  }
}
