// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB194GBuLhpU_cjhBdF_XQgWvCmgZIIots',
    appId: '1:317679762375:web:934ba1978b23a8da0337e2',
    messagingSenderId: '317679762375',
    projectId: 'valerion-55414',
    authDomain: 'valerion-55414.firebaseapp.com',
    storageBucket: 'valerion-55414.firebasestorage.app',
    measurementId: 'G-3RR1MZC97X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALbcxFo0B9cxMYVSQy_bm4v51wtn1HFXw',
    appId: '1:317679762375:android:a226a0fa8c694a990337e2',
    messagingSenderId: '317679762375',
    projectId: 'valerion-55414',
    storageBucket: 'valerion-55414.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkd-rausSvGLV4ly6IGGHcD7etlrAe9cw',
    appId: '1:317679762375:ios:9ac55d4bc597d3280337e2',
    messagingSenderId: '317679762375',
    projectId: 'valerion-55414',
    storageBucket: 'valerion-55414.firebasestorage.app',
    androidClientId: '317679762375-5mlldt5rt8pm1lgv597uj3jtutv51mca.apps.googleusercontent.com',
    iosClientId: '317679762375-q19eng4di94pbqrgrqfqg1srcvmeasj4.apps.googleusercontent.com',
    iosBundleId: 'com.osirion.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkd-rausSvGLV4ly6IGGHcD7etlrAe9cw',
    appId: '1:317679762375:ios:9ac55d4bc597d3280337e2',
    messagingSenderId: '317679762375',
    projectId: 'valerion-55414',
    storageBucket: 'valerion-55414.firebasestorage.app',
    androidClientId: '317679762375-5mlldt5rt8pm1lgv597uj3jtutv51mca.apps.googleusercontent.com',
    iosClientId: '317679762375-q19eng4di94pbqrgrqfqg1srcvmeasj4.apps.googleusercontent.com',
    iosBundleId: 'com.osirion.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB194GBuLhpU_cjhBdF_XQgWvCmgZIIots',
    appId: '1:317679762375:web:4f28beb92903954f0337e2',
    messagingSenderId: '317679762375',
    projectId: 'valerion-55414',
    authDomain: 'valerion-55414.firebaseapp.com',
    storageBucket: 'valerion-55414.firebasestorage.app',
    measurementId: 'G-2F9WHFT1PX',
  );
}