import 'package:flutter/material.dart';
import 'relic.dart';

extension RelicLocalization on Relic {
  String getLocalizedName(BuildContext context) {
    final isEn = Localizations.localeOf(context).languageCode == 'en';
    if (!isEn) return name;
    
    switch (id) {
      case 'title_perseverant': return 'The Perseverant';
      case 'title_titan': return 'Iron Titan';
      case 'halo_feu': return 'Halo of Fire';
      case 'aura_brume': return 'Morning Mist';
      case 'halo_sylvestre': return 'Sylvan Halo';
      case 'halo_glacial': return 'Glacial Halo';
      case 'aura_vents': return 'Swirling Winds';
      case 'fx_carbone': return 'Carbon Particles';
      case 'aura_magnetique': return 'Magnetic Sphere';
      case 'halo_foudroyant': return 'Lightning Halo';
      case 'aura_bio': return 'Bio-luminescent Glow';
      case 'halo_solaire': return 'Solar Radiation';
      case 'fx_neon': return 'Neon Trail';
      case 'aura_volcanique': return 'Volcanic Aura';
      case 'aura_cristalline': return 'Crystalline Aura';
      case 'fx_cyber': return 'Cybernetic Shine';
      case 'aura_purete': return 'Aura of Purity';
      case 'halo_plasma': return 'Plasma Halo';
      case 'aura_quantique': return 'Quantum Resonance';
      case 'aura_ombre': return 'Stealthy Shadow';
      case 'boost_motivation': return 'Spark of Motivation';
      case 'boost_seve': return 'Energizing Sap';
      case 'boost_vitalite2': return 'Crystal of Vitality';
      case 'boost_recuperation': return 'Recovery Potion';
      case 'boost_florale': return 'Floral Essence';
      case 'boost_fer': return 'Iron Infusion';
      case 'boost_bouclier': return 'Thermal Shield';
      case 'boost_ticket_double': return 'Double Reward Ticket';
      case 'boost_resilience': return 'Crystal of Resilience';
      case 'boost_purificateur': return 'Purifying Filter';
      case 'boost_croissance': return 'Seed of Growth';
      case 'boost_batterie': return 'High Voltage Battery';
      case 'boost_catalyseur': return 'Carbon Catalyst';
      case 'boost_super_condensateur': return 'Super Capacitor';
      case 'title_shop_1': return 'Apprentice Blacksmith';
      case 'title_shop_3': return 'Ember Blower';
      case 'title_shop_4': return 'Ardent Poker';
      case 'title_shop_5': return 'Iron Sculptor';
      case 'title_shop_6': return 'Anvil Master';
      case 'title_shop_8': return 'Blade Craftsman';
      case 'title_shop_9': return 'War Blacksmith';
      case 'title_shop_10': return 'Lord of the Forge';
      case 'title_shop_12': return 'Stellar Blacksmith';
      case 'title_shop_13': return 'Guardian of the Primal Fire';
      case 'title_shop_14': return 'World Maker';
      case 'title_lvl1': return 'Novice';
      case 'title_lvl2': return 'Initiate';
      case 'title_lvl3': return 'Walker';
      case 'title_lvl4': return 'Apprentice';
      case 'title_lvl5': return 'Disciple';
      case 'title_lvl6': return 'Practitioner';
      case 'title_lvl7': return 'Explorer';
      case 'title_lvl8': return 'Challenger';
      case 'title_lvl9': return 'Fighter';
      case 'title_lvl10': return 'Warrior';
      case 'title_lvl11': return 'Athlete';
      case 'title_lvl12': return 'Defender';
      case 'title_lvl13': return 'Protector';
      case 'title_lvl14': return 'Soldier';
      case 'title_lvl15': return 'Spartan';
      case 'title_lvl16': return 'Centurion';
      case 'title_lvl17': return 'Veteran';
      case 'title_lvl18': return 'Guardian';
      case 'title_lvl19': return 'Sentinel';
      case 'title_lvl20': return 'Knight';
      case 'title_lvl22': return 'Paladin';
      case 'title_lvl24': return 'Champion';
      case 'title_lvl26': return 'Elite';
      case 'title_lvl28': return 'Hero';
      case 'title_lvl30': return 'Legend';
      case 'title_lvl32': return 'Myth';
      case 'title_lvl34': return 'Master';
      case 'title_lvl36': return 'Grand Master';
      case 'title_lvl38': return 'Prodigy';
      case 'title_lvl40': return 'Demigod';
      case 'title_lvl42': return 'Immortal';
      case 'title_lvl45': return 'Colossus';
      case 'title_lvl48': return 'Titan';
      case 'title_lvl50': return 'God of War';
      case 'title_lvl55': return 'Guardian of Earth';
      case 'title_lvl60': return 'Force of Nature';
      case 'title_lvl65': return 'Lord of Elements';
      case 'title_lvl70': return 'Master of Gravity';
      case 'title_lvl75': return 'Cosmic Entity';
      case 'title_lvl80': return 'Blazing Star';
      case 'title_lvl85': return 'Supernova';
      case 'title_lvl90': return 'Galactic';
      case 'title_lvl95': return 'Supreme Being';
      case 'title_lvl100': return 'Supreme Alpha';
      case 'title_lvl110': return 'Primordial';
      case 'title_lvl120': return 'Nexus';
      case 'title_lvl130': return 'Singularity';
      case 'title_lvl150': return 'Omega';
      default: return name;
    }
  }

  String getLocalizedDescription(BuildContext context) {
    final isEn = Localizations.localeOf(context).languageCode == 'en';
    if (!isEn) return description;
    
    switch (id) {
      case 'title_perseverant': return 'Proves your continuous determination.';
      case 'title_titan': return 'Reserved for unstoppable machines.';
      case 'halo_feu': return 'An incandescent aura burns around you.';
      case 'aura_brume': return 'A mysterious and refreshing aura.';
      case 'halo_sylvestre': return 'The force of nature surrounds you.';
      case 'halo_glacial': return 'A polar cold emanates from your presence.';
      case 'aura_vents': return 'An aura of swirling winds.';
      case 'fx_carbone': return 'Carbon shards float around you.';
      case 'aura_magnetique': return 'A magnetic force repels the weak.';
      case 'halo_foudroyant': return 'Electric arcs travel across your profile.';
      case 'aura_bio': return 'An organic and soothing glow.';
      case 'halo_solaire': return 'Blinding solar radiation.';
      case 'fx_neon': return 'A dazzling cyberpunk style.';
      case 'aura_volcanique': return 'An uncontrollable eruptive power.';
      case 'aura_cristalline': return 'Geometric perfection and absolute purity.';
      case 'fx_cyber': return 'Technology merges with your mind.';
      case 'aura_purete': return 'A divine clarity without any flaw.';
      case 'halo_plasma': return 'Superheated energy ready to explode.';
      case 'aura_quantique': return 'You exist in multiple realities at once.';
      case 'aura_ombre': return 'The densest darkness envelops you.';
      case 'boost_motivation': return '(Consumable) Small regeneration of motivation.';
      case 'boost_seve': return '(Consumable) Reduces recovery time by 20%.';
      case 'boost_vitalite2': return '(Consumable) Vitality bonus.';
      case 'boost_recuperation': return '(Consumable) Restores 50% of the twin\'s health bar.';
      case 'boost_florale': return '(Consumable) Minor floral bonus.';
      case 'boost_fer': return '(Consumable) Increased resistance to environmental penalties.';
      case 'boost_bouclier': return '(Consumable) Protects the current streak from being broken.';
      case 'boost_ticket_double': return '(Consumable) x2 Aether on the next validated session.';
      case 'boost_resilience': return '(Consumable) Blocks an Aether loss.';
      case 'boost_purificateur': return '(Consumable) Converts an environmental penalty into a bonus.';
      case 'boost_croissance': return '(Consumable) +25% Aether gain.';
      case 'boost_batterie': return '(Consumable) Instantly restores all energy.';
      case 'boost_catalyseur': return '(Consumable) Multiplies carbon acquisition by 2.';
      case 'boost_super_condensateur': return '(Consumable) Stores the week\'s gains to double them.';
      case 'title_shop_1': return 'He who begins to wield the hammer.';
      case 'title_shop_3': return 'Master of the forge\'s flames.';
      case 'title_shop_4': return 'The metal bends to your will.';
      case 'title_shop_5': return 'The art of shaping raw iron.';
      case 'title_shop_6': return 'Your strikes echo throughout the land.';
      case 'title_shop_8': return 'Every weapon you forge has a soul.';
      case 'title_shop_9': return 'Entire armies depend on your art.';
      case 'title_shop_10': return 'Nothing is forged without your approval.';
      case 'title_shop_12': return 'Your materials come from fallen stars.';
      case 'title_shop_13': return 'You forge with the primordial element.';
      case 'title_shop_14': return 'Your anvil is the earth\'s crust itself.';
      case 'title_lvl1': return 'Reached level 1.';
      case 'title_lvl2': return 'Reached level 2.';
      case 'title_lvl3': return 'Reached level 3.';
      case 'title_lvl4': return 'Reached level 4.';
      case 'title_lvl5': return 'Reached level 5.';
      case 'title_lvl6': return 'Reached level 6.';
      case 'title_lvl7': return 'Reached level 7.';
      case 'title_lvl8': return 'Reached level 8.';
      case 'title_lvl9': return 'Reached level 9.';
      case 'title_lvl10': return 'Reached level 10.';
      case 'title_lvl11': return 'Reached level 11.';
      case 'title_lvl12': return 'Reached level 12.';
      case 'title_lvl13': return 'Reached level 13.';
      case 'title_lvl14': return 'Reached level 14.';
      case 'title_lvl15': return 'Reached level 15.';
      case 'title_lvl16': return 'Reached level 16.';
      case 'title_lvl17': return 'Reached level 17.';
      case 'title_lvl18': return 'Reached level 18.';
      case 'title_lvl19': return 'Reached level 19.';
      case 'title_lvl20': return 'Reached level 20.';
      case 'title_lvl22': return 'Reached level 22.';
      case 'title_lvl24': return 'Reached level 24.';
      case 'title_lvl26': return 'Reached level 26.';
      case 'title_lvl28': return 'Reached level 28.';
      case 'title_lvl30': return 'Reached level 30.';
      case 'title_lvl32': return 'Reached level 32.';
      case 'title_lvl34': return 'Reached level 34.';
      case 'title_lvl36': return 'Reached level 36.';
      case 'title_lvl38': return 'Reached level 38.';
      case 'title_lvl40': return 'Reached level 40.';
      case 'title_lvl42': return 'Reached level 42.';
      case 'title_lvl45': return 'Reached level 45.';
      case 'title_lvl48': return 'Reached level 48.';
      case 'title_lvl50': return 'Reached level 50.';
      case 'title_lvl55': return 'Reached level 55.';
      case 'title_lvl60': return 'Reached level 60.';
      case 'title_lvl65': return 'Reached level 65.';
      case 'title_lvl70': return 'Reached level 70.';
      case 'title_lvl75': return 'Reached level 75.';
      case 'title_lvl80': return 'Reached level 80.';
      case 'title_lvl85': return 'Reached level 85.';
      case 'title_lvl90': return 'Reached level 90.';
      case 'title_lvl95': return 'Reached level 95.';
      case 'title_lvl100': return 'Reached level 100.';
      case 'title_lvl110': return 'Reached level 110.';
      case 'title_lvl120': return 'Reached level 120.';
      case 'title_lvl130': return 'Reached level 130.';
      case 'title_lvl150': return 'Reached level 150.';
      default: return description;
    }
  }
}
