import 'package:flutter/material.dart';
import '../../features/arsenal/models/relic.dart';

final List<Relic> defaultRelicsToSeed = [
  // --- TITRES (Boutique) ---
  const Relic(
    id: 'title_perseverant',
    name: 'Le Persévérant',
    description: 'Prouve votre détermination continue.',
    icon: Icons.directions_run,
    color: Colors.greenAccent,
    cost: 100,
    type: 'title',
  ),
  const Relic(
    id: 'title_eveille',
    name: "L'Éveillé",
    description: 'Titre spirituel pour un esprit clair.',
    icon: Icons.remove_red_eye,
    color: Colors.blueAccent,
    cost: 300,
    type: 'title',
  ),
  const Relic(
    id: 'title_titan',
    name: 'Titan de Fer',
    description: 'Réservé aux machines inarrêtables.',
    icon: Icons.fitness_center,
    color: Colors.redAccent,
    cost: 1000,
    type: 'title',
  ),
  const Relic(
    id: 'title_intouchable',
    name: "L'Intouchable",
    description: 'Aucune excuse ne peut vous atteindre.',
    icon: Icons.shield_moon,
    color: Colors.indigoAccent,
    cost: 1500,
    type: 'title',
  ),
  const Relic(
    id: 'title_eclair',
    name: "L'Éclair",
    description: 'Pour ceux qui agissent vite et bien.',
    icon: Icons.bolt,
    color: Colors.yellow,
    cost: 500,
    type: 'title',
  ),

  // --- HALOS & AURAS ---
  const Relic(
    id: 'halo_feu',
    name: 'Halo de Feu',
    description: 'Une aura incandescente brûle autour de vous.',
    icon: Icons.local_fire_department,
    color: Colors.deepOrangeAccent,
    cost: 2500,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_brume',
    name: 'Brume Matinale',
    description: 'Une aura mystérieuse et rafraîchissante.',
    icon: Icons.cloud,
    color: Colors.white60,
    cost: 3000,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_sylvestre',
    name: 'Halo Sylvestre',
    description: 'La force de la nature vous entoure.',
    icon: Icons.eco,
    color: Colors.lightGreenAccent,
    cost: 3500,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_epines',
    name: 'Couronne d\'Épines',
    description: 'Un symbole de sacrifice et de résilience.',
    icon: Icons.grass,
    color: Colors.brown,
    cost: 4000,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_glacial',
    name: 'Halo Glacial',
    description: 'Un froid polaire émane de votre présence.',
    icon: Icons.ac_unit,
    color: Colors.cyanAccent,
    cost: 4500,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_vents',
    name: 'Vents Tourbillonnants',
    description: 'Une aura d\'agilité et de légèreté perpétuelle.',
    icon: Icons.air,
    color: Colors.lightBlue,
    cost: 5500,
    type: 'halo',
  ),
  const Relic(
    id: 'fx_carbone',
    name: 'Particules de Carbone',
    description: 'Des éclats de carbone flottent autour de vous.',
    icon: Icons.scatter_plot,
    color: Colors.grey,
    cost: 6500,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_magnetique',
    name: 'Sphère Magnétique',
    description: 'Une force d\'attraction irrésistible.',
    icon: Icons.radar,
    color: Colors.purple,
    cost: 7500,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_foudroyant',
    name: 'Halo Foudroyant',
    description: 'Des arcs électriques parcourent votre profil.',
    icon: Icons.bolt,
    color: Colors.yellow,
    cost: 8500,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_bio',
    name: 'Lueur Bio-luminescente',
    description: 'Une lueur organique et apaisante.',
    icon: Icons.wb_twilight,
    color: Colors.tealAccent,
    cost: 10000,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_solaire',
    name: 'Rayonnement Solaire',
    description: 'L\'énergie pure de l\'astre du jour.',
    icon: Icons.wb_sunny,
    color: Colors.orangeAccent,
    cost: 12000,
    type: 'halo',
  ),
  const Relic(
    id: 'fx_neon',
    name: 'Traînée de Néon',
    description: 'Un style cyberpunk éclatant.',
    icon: Icons.gesture,
    color: Colors.pinkAccent,
    cost: 15000,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_volcanique',
    name: 'Aura Volcanique',
    description: 'Une puissance éruptive incontrôlable.',
    icon: Icons.volcano,
    color: Colors.redAccent,
    cost: 18000,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_cristalline',
    name: 'Aura Cristalline',
    description: 'La perfection géométrique et la pureté absolue.',
    icon: Icons.diamond,
    color: Colors.lightBlueAccent,
    cost: 22000,
    type: 'halo',
  ),
  const Relic(
    id: 'fx_cyber',
    name: 'Éclat Cybernétique',
    description: 'La technologie fusionne avec votre esprit.',
    icon: Icons.memory,
    color: Colors.greenAccent,
    cost: 28000,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_purete',
    name: 'Aura de Pureté',
    description: 'Une clarté divine sans aucune faille.',
    icon: Icons.brightness_high,
    color: Colors.white,
    cost: 35000,
    type: 'halo',
  ),
  const Relic(
    id: 'halo_plasma',
    name: 'Halo Plasma',
    description: 'Une énergie surchauffée prête à exploser.',
    icon: Icons.lens_blur,
    color: Colors.purpleAccent,
    cost: 45000,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_quantique',
    name: 'Résonance Quantique',
    description: 'Vous existez dans plusieurs réalités à la fois.',
    icon: Icons.all_inclusive,
    color: Colors.indigoAccent,
    cost: 60000,
    type: 'halo',
  ),
  const Relic(
    id: 'aura_ombre',
    name: 'Ombre Furtive',
    description: 'Les ténèbres les plus denses vous enveloppent.',
    icon: Icons.nights_stay,
    color: Colors.black87,
    cost: 80000,
    type: 'halo',
  ),
  const Relic(
    id: 'fx_etoiles',
    name: 'Poussière d\'Étoiles',
    description: 'Le cosmos tout entier vous appartient.',
    icon: Icons.auto_awesome,
    color: Colors.amberAccent,
    cost: 120000,
    type: 'halo',
  ),

  // --- BOOSTS ---
  const Relic(
    id: 'boost_motivation',
    name: 'Éclat de Motivation',
    description: '(Consommable) Petite régénération d\'énergie (Jumeau).',
    icon: Icons.battery_charging_full,
    color: Colors.greenAccent,
    cost: 150,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_seve',
    name: 'Sève Énergisante',
    description: '(Consommable) Réduit le temps de récupération de 20%.',
    icon: Icons.grass,
    color: Colors.lightGreen,
    cost: 200,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_vitalite2',
    name: 'Cristal de Vitalité',
    description: '(Consommable) Bonus d\'endurance léger pour le prochain défi.',
    icon: Icons.diamond,
    color: Colors.pinkAccent,
    cost: 250,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_echange',
    name: 'Jeton d\'Échange',
    description: '(Consommable) Permet de relancer une quête journalière non souhaitée.',
    icon: Icons.swap_horiz,
    color: Colors.orange,
    cost: 300,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_recuperation',
    name: 'Potion de Récupération',
    description: '(Consommable) Restaure 50% de la jauge de santé du jumeau.',
    icon: Icons.local_hospital,
    color: Colors.redAccent,
    cost: 350,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_florale',
    name: 'Essence Florale',
    description: '(Consommable) Bonus mineur d\'impact écologique (+5%).',
    icon: Icons.local_florist,
    color: Colors.purpleAccent,
    cost: 400,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_aigle',
    name: 'Souffle de l\'Aigle',
    description: '(Consommable) Augmente la précision/score d\'une session de 10%.',
    icon: Icons.air,
    color: Colors.cyan,
    cost: 450,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_oxygene',
    name: 'Élixir d\'Oxygène',
    description: '(Consommable) Annule la fatigue virtuelle du prochain entraînement.',
    icon: Icons.water_drop,
    color: Colors.blueAccent,
    cost: 500,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_adrenaline',
    name: 'Boost d\'Adrénaline',
    description: '(Consommable) +25% d\'Aether gagnés pendant 2 heures.',
    icon: Icons.flash_on,
    color: Colors.yellowAccent,
    cost: 600,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_fer',
    name: 'Infusion de Fer',
    description: '(Consommable) Résistance accrue aux malus d\'inactivité (24h).',
    icon: Icons.fitness_center,
    color: Colors.grey,
    cost: 700,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_bouclier',
    name: 'Bouclier Thermique',
    description: '(Consommable) Protège la série d\'entraînements (Streak) pour 1 jour raté.',
    icon: Icons.shield,
    color: Colors.deepOrange,
    cost: 850,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_ticket_double',
    name: 'Ticket Double Gain',
    description: '(Consommable) x2 Aether sur la prochaine session validée.',
    icon: Icons.confirmation_number,
    color: Colors.amber,
    cost: 1000,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_resilience',
    name: 'Cristal de Résilience',
    description: '(Consommable) Bloque une perte de points d\'impact sur le jumeau.',
    icon: Icons.security,
    color: Colors.blueGrey,
    cost: 1200,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_purificateur',
    name: 'Filtre Purificateur',
    description: '(Consommable) Convertit un malus environnemental en bonus.',
    icon: Icons.filter_alt,
    color: Colors.teal,
    cost: 1500,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_croissance',
    name: 'Graine de Croissance',
    description: '(Consommable) +25% d\'XP générée sur 24h.',
    icon: Icons.eco,
    color: Colors.lightGreen,
    cost: 1800,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_batterie',
    name: 'Batterie Haute Tension',
    description: '(Consommable) Restaure instantanément toute l\'énergie du jumeau.',
    icon: Icons.battery_alert,
    color: Colors.yellow,
    cost: 2000,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_catalyseur',
    name: 'Catalyseur de Carbone',
    description: '(Consommable) Multiplie l\'impact environnemental par 1.5 (24h).',
    icon: Icons.science,
    color: Colors.deepPurpleAccent,
    cost: 2500,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_multiplicateur',
    name: 'Multiplicateur d\'Impact',
    description: '(Consommable) Double absolument tous les gains de la journée.',
    icon: Icons.exposure_plus_2,
    color: Colors.amberAccent,
    cost: 3500,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_apesanteur',
    name: 'Poudre d\'Apesanteur',
    description: '(Consommable) Valide instantanément un défi difficile sans le faire.',
    icon: Icons.cloud,
    color: Colors.white70,
    cost: 5000,
    type: 'boost',
  ),
  const Relic(
    id: 'boost_super_condensateur',
    name: 'Super-Condensateur',
    description: '(Consommable) Emmagasine les gains de la semaine pour les doubler.',
    icon: Icons.memory,
    color: Colors.cyan,
    cost: 8000,
    type: 'boost',
  ),

  // --- TITRES ACHETABLES (BOUTIQUE) ---
  const Relic(
    id: 'title_shop_1',
    name: 'Apprenti Forgeron',
    description: 'Celui qui commence à manier le marteau.',
    icon: Icons.hardware,
    color: Colors.brown,
    cost: 1000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_2',
    name: 'Frappeur d\'Acier',
    description: 'Le métal commence à plier sous votre volonté.',
    icon: Icons.construction,
    color: Colors.blueGrey,
    cost: 2500,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_3',
    name: 'Souffleur de Braises',
    description: 'Maître des flammes de l\'enclume.',
    icon: Icons.local_fire_department,
    color: Colors.orange,
    cost: 5000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_4',
    name: 'Tisonnier Ardent',
    description: 'L\'artisan qui forge dans la chaleur la plus intense.',
    icon: Icons.fireplace,
    color: Colors.deepOrange,
    cost: 8000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_5',
    name: 'Sculpteur de Fer',
    description: 'L\'acier est comme de l\'argile entre vos mains.',
    icon: Icons.precision_manufacturing,
    color: Colors.grey,
    cost: 12000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_6',
    name: 'Maître Enclume',
    description: 'Vos coups résonnent dans toute la contrée.',
    icon: Icons.anchor,
    color: Colors.blueAccent,
    cost: 20000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_7',
    name: 'Façonneur d\'Armes',
    description: 'Créateur des lames les plus tranchantes.',
    icon: Icons.colorize,
    color: Colors.cyan,
    cost: 35000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_8',
    name: 'Artisan de la Lame',
    description: 'Chaque arme que vous forgez a une âme.',
    icon: Icons.architecture,
    color: Colors.teal,
    cost: 50000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_9',
    name: 'Forgeron de Guerre',
    description: 'Les armées entières dépendent de votre art.',
    icon: Icons.shield,
    color: Colors.red,
    cost: 75000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_10',
    name: 'Seigneur de la Forge',
    description: 'Rien ne se forge sans votre approbation.',
    icon: Icons.castle,
    color: Colors.amber,
    cost: 100000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_11',
    name: 'Créateur d\'Artéfacts',
    description: 'Vous forgez bien plus que de simples armes.',
    icon: Icons.auto_awesome,
    color: Colors.purpleAccent,
    cost: 250000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_12',
    name: 'Forgeron Stellaire',
    description: 'Vos matériaux proviennent des étoiles tombées.',
    icon: Icons.star,
    color: Colors.indigoAccent,
    cost: 500000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_13',
    name: 'Gardien du Feu Primordial',
    description: 'Vous forgez à l\'aide de l\'énergie même de la création.',
    icon: Icons.whatshot,
    color: Colors.redAccent,
    cost: 1000000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_14',
    name: 'Faiseur de Mondes',
    description: 'Votre enclume est la croûte terrestre elle-même.',
    icon: Icons.public,
    color: Colors.greenAccent,
    cost: 2500000,
    type: 'title',
  ),
  const Relic(
    id: 'title_shop_15',
    name: 'Démiurge de l\'Acier',
    description: 'Une légende vivante, le dieu des forgerons.',
    icon: Icons.diamond,
    color: Colors.cyanAccent,
    cost: 5000000,
    type: 'title',
  ),

  // --- TITRES DÉBLOCABLES PAR NIVEAU ---
  const Relic(
    id: 'title_lvl1',
    name: 'Novice',
    description: 'Niveau 1 atteint.',
    icon: Icons.star_border,
    color: Colors.white30,
    cost: 0,
    type: 'title',
    requiredLevel: 1,
  ),
  const Relic(
    id: 'title_lvl2',
    name: 'Initié(e)',
    description: 'Niveau 2 atteint.',
    icon: Icons.school,
    color: Colors.white54,
    cost: 0,
    type: 'title',
    requiredLevel: 2,
  ),
  const Relic(
    id: 'title_lvl3',
    name: 'Marcheur',
    description: 'Niveau 3 atteint.',
    icon: Icons.directions_walk,
    color: Colors.white70,
    cost: 0,
    type: 'title',
    requiredLevel: 3,
  ),
  const Relic(
    id: 'title_lvl4',
    name: 'Apprenti(e)',
    description: 'Niveau 4 atteint.',
    icon: Icons.book,
    color: Colors.lightGreen,
    cost: 0,
    type: 'title',
    requiredLevel: 4,
  ),
  const Relic(
    id: 'title_lvl5',
    name: 'Disciple',
    description: 'Niveau 5 atteint.',
    icon: Icons.sports_martial_arts,
    color: Colors.green,
    cost: 0,
    type: 'title',
    requiredLevel: 5,
  ),
  const Relic(
    id: 'title_lvl6',
    name: 'Pratiquant(e)',
    description: 'Niveau 6 atteint.',
    icon: Icons.fitness_center,
    color: Colors.teal,
    cost: 0,
    type: 'title',
    requiredLevel: 6,
  ),
  const Relic(
    id: 'title_lvl7',
    name: 'Explorateur',
    description: 'Niveau 7 atteint.',
    icon: Icons.explore,
    color: Colors.cyan,
    cost: 0,
    type: 'title',
    requiredLevel: 7,
  ),
  const Relic(
    id: 'title_lvl8',
    name: 'Challenger',
    description: 'Niveau 8 atteint.',
    icon: Icons.flag,
    color: Colors.blueAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 8,
  ),
  const Relic(
    id: 'title_lvl9',
    name: 'Combattant(e)',
    description: 'Niveau 9 atteint.',
    icon: Icons.sports_kabaddi,
    color: Colors.blue,
    cost: 0,
    type: 'title',
    requiredLevel: 9,
  ),
  const Relic(
    id: 'title_lvl10',
    name: 'Guerrier(e)',
    description: 'Niveau 10 atteint.',
    icon: Icons.shield,
    color: Colors.indigo,
    cost: 0,
    type: 'title',
    requiredLevel: 10,
  ),
  const Relic(
    id: 'title_lvl11',
    name: 'Athlète',
    description: 'Niveau 11 atteint.',
    icon: Icons.run_circle,
    color: Colors.deepPurple,
    cost: 0,
    type: 'title',
    requiredLevel: 11,
  ),
  const Relic(
    id: 'title_lvl12',
    name: 'Défenseur',
    description: 'Niveau 12 atteint.',
    icon: Icons.security,
    color: Colors.purple,
    cost: 0,
    type: 'title',
    requiredLevel: 12,
  ),
  const Relic(
    id: 'title_lvl13',
    name: 'Protecteur',
    description: 'Niveau 13 atteint.',
    icon: Icons.health_and_safety,
    color: Colors.pink,
    cost: 0,
    type: 'title',
    requiredLevel: 13,
  ),
  const Relic(
    id: 'title_lvl14',
    name: 'Soldat',
    description: 'Niveau 14 atteint.',
    icon: Icons.military_tech,
    color: Colors.redAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 14,
  ),
  const Relic(
    id: 'title_lvl15',
    name: 'Spartiate',
    description: 'Niveau 15 atteint.',
    icon: Icons.hardware,
    color: Colors.red,
    cost: 0,
    type: 'title',
    requiredLevel: 15,
  ),
  const Relic(
    id: 'title_lvl16',
    name: 'Centurion',
    description: 'Niveau 16 atteint.',
    icon: Icons.workspace_premium,
    color: Colors.deepOrange,
    cost: 0,
    type: 'title',
    requiredLevel: 16,
  ),
  const Relic(
    id: 'title_lvl17',
    name: 'Vétéran',
    description: 'Niveau 17 atteint.',
    icon: Icons.badge,
    color: Colors.orange,
    cost: 0,
    type: 'title',
    requiredLevel: 17,
  ),
  const Relic(
    id: 'title_lvl18',
    name: 'Gardien(ne)',
    description: 'Niveau 18 atteint.',
    icon: Icons.lock,
    color: Colors.amber,
    cost: 0,
    type: 'title',
    requiredLevel: 18,
  ),
  const Relic(
    id: 'title_lvl19',
    name: 'Sentinelle',
    description: 'Niveau 19 atteint.',
    icon: Icons.visibility,
    color: Colors.yellow,
    cost: 0,
    type: 'title',
    requiredLevel: 19,
  ),
  const Relic(
    id: 'title_lvl20',
    name: 'Chevalier(e)',
    description: 'Niveau 20 atteint.',
    icon: Icons.gavel,
    color: Colors.lightGreenAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 20,
  ),
  const Relic(
    id: 'title_lvl22',
    name: 'Paladin',
    description: 'Niveau 22 atteint.',
    icon: Icons.healing,
    color: Colors.greenAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 22,
  ),
  const Relic(
    id: 'title_lvl24',
    name: 'Champion(ne)',
    description: 'Niveau 24 atteint.',
    icon: Icons.emoji_events,
    color: Colors.cyanAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 24,
  ),
  const Relic(
    id: 'title_lvl26',
    name: 'Élite',
    description: 'Niveau 26 atteint.',
    icon: Icons.star,
    color: Colors.blueAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 26,
  ),
  const Relic(
    id: 'title_lvl28',
    name: 'Héros / Héroïne',
    description: 'Niveau 28 atteint.',
    icon: Icons.flash_on,
    color: Colors.indigoAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 28,
  ),
  const Relic(
    id: 'title_lvl30',
    name: 'Légende',
    description: 'Niveau 30 atteint.',
    icon: Icons.local_fire_department,
    color: Colors.purpleAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 30,
  ),
  const Relic(
    id: 'title_lvl32',
    name: 'Mythe',
    description: 'Niveau 32 atteint.',
    icon: Icons.auto_stories,
    color: Colors.pinkAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 32,
  ),
  const Relic(
    id: 'title_lvl34',
    name: 'Maître',
    description: 'Niveau 34 atteint.',
    icon: Icons.school,
    color: Colors.redAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 34,
  ),
  const Relic(
    id: 'title_lvl36',
    name: 'Grand Maître',
    description: 'Niveau 36 atteint.',
    icon: Icons.account_balance,
    color: Colors.orangeAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 36,
  ),
  const Relic(
    id: 'title_lvl38',
    name: 'Prodige',
    description: 'Niveau 38 atteint.',
    icon: Icons.lightbulb,
    color: Colors.yellowAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 38,
  ),
  const Relic(
    id: 'title_lvl40',
    name: 'Demi-Dieu',
    description: 'Niveau 40 atteint.',
    icon: Icons.bolt,
    color: Colors.cyan,
    cost: 0,
    type: 'title',
    requiredLevel: 40,
  ),
  const Relic(
    id: 'title_lvl42',
    name: 'Immortel(le)',
    description: 'Niveau 42 atteint.',
    icon: Icons.all_inclusive,
    color: Colors.teal,
    cost: 0,
    type: 'title',
    requiredLevel: 42,
  ),
  const Relic(
    id: 'title_lvl45',
    name: 'Colosse',
    description: 'Niveau 45 atteint.',
    icon: Icons.landscape,
    color: Colors.brown,
    cost: 0,
    type: 'title',
    requiredLevel: 45,
  ),
  const Relic(
    id: 'title_lvl48',
    name: 'Titan',
    description: 'Niveau 48 atteint.',
    icon: Icons.terrain,
    color: Colors.grey,
    cost: 0,
    type: 'title',
    requiredLevel: 48,
  ),
  const Relic(
    id: 'title_lvl50',
    name: 'Dieu de la Guerre',
    description: 'Niveau 50 atteint.',
    icon: Icons.whatshot,
    color: Colors.deepOrange,
    cost: 0,
    type: 'title',
    requiredLevel: 50,
  ),
  const Relic(
    id: 'title_lvl55',
    name: 'Gardien de la Terre',
    description: 'Niveau 55 atteint.',
    icon: Icons.public,
    color: Colors.green,
    cost: 0,
    type: 'title',
    requiredLevel: 55,
  ),
  const Relic(
    id: 'title_lvl60',
    name: 'Force de la Nature',
    description: 'Niveau 60 atteint.',
    icon: Icons.eco,
    color: Colors.lightGreen,
    cost: 0,
    type: 'title',
    requiredLevel: 60,
  ),
  const Relic(
    id: 'title_lvl65',
    name: 'Seigneur des Éléments',
    description: 'Niveau 65 atteint.',
    icon: Icons.ac_unit,
    color: Colors.blue,
    cost: 0,
    type: 'title',
    requiredLevel: 65,
  ),
  const Relic(
    id: 'title_lvl70',
    name: 'Maître de la Gravité',
    description: 'Niveau 70 atteint.',
    icon: Icons.blur_on,
    color: Colors.deepPurple,
    cost: 0,
    type: 'title',
    requiredLevel: 70,
  ),
  const Relic(
    id: 'title_lvl75',
    name: 'Entité Cosmique',
    description: 'Niveau 75 atteint.',
    icon: Icons.auto_awesome,
    color: Colors.purple,
    cost: 0,
    type: 'title',
    requiredLevel: 75,
  ),
  const Relic(
    id: 'title_lvl80',
    name: 'Astre Flamboyant',
    description: 'Niveau 80 atteint.',
    icon: Icons.wb_sunny,
    color: Colors.orange,
    cost: 0,
    type: 'title',
    requiredLevel: 80,
  ),
  const Relic(
    id: 'title_lvl85',
    name: 'Supernova',
    description: 'Niveau 85 atteint.',
    icon: Icons.flare,
    color: Colors.red,
    cost: 0,
    type: 'title',
    requiredLevel: 85,
  ),
  const Relic(
    id: 'title_lvl90',
    name: 'Galactique',
    description: 'Niveau 90 atteint.',
    icon: Icons.rocket_launch,
    color: Colors.indigo,
    cost: 0,
    type: 'title',
    requiredLevel: 90,
  ),
  const Relic(
    id: 'title_lvl95',
    name: 'Être Suprême',
    description: 'Niveau 95 atteint.',
    icon: Icons.diamond,
    color: Colors.amber,
    cost: 0,
    type: 'title',
    requiredLevel: 95,
  ),
  const Relic(
    id: 'title_lvl100',
    name: 'Alpha Suprême',
    description: 'Niveau 100 atteint.',
    icon: Icons.workspace_premium,
    color: Colors.cyanAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 100,
  ),
  const Relic(
    id: 'title_lvl110',
    name: 'Primordial',
    description: 'Niveau 110 atteint.',
    icon: Icons.brightness_7,
    color: Colors.deepOrangeAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 110,
  ),
  const Relic(
    id: 'title_lvl120',
    name: 'Nexus',
    description: 'Niveau 120 atteint.',
    icon: Icons.hub,
    color: Colors.tealAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 120,
  ),
  const Relic(
    id: 'title_lvl130',
    name: 'Singularité',
    description: 'Niveau 130 atteint.',
    icon: Icons.trip_origin,
    color: Colors.purpleAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 130,
  ),
  const Relic(
    id: 'title_lvl140',
    name: 'L\'Infini',
    description: 'Niveau 140 atteint.',
    icon: Icons.all_inclusive,
    color: Colors.indigoAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 140,
  ),
  const Relic(
    id: 'title_lvl150',
    name: 'Oméga',
    description: 'Niveau 150 atteint.',
    icon: Icons.adjust,
    color: Colors.redAccent,
    cost: 0,
    type: 'title',
    requiredLevel: 150,
  ),
  const Relic(
    id: 'title_lvl200',
    name: 'L\'Absolu',
    description: 'Niveau 200 atteint. Le sommet de toute existence.',
    icon: Icons.diamond,
    color: Colors.white,
    cost: 0,
    type: 'title',
    requiredLevel: 200,
  ),
];
